[client]
remote_addr = "80.225.248.6:2333"
heartbeat_timeout = 20
retry_interval = 1

[client.transport]
type = "tcp"

[client.transport.tcp]
keepalive_secs = 15
keepalive_interval = 5

[client.services.http]
token = "JD@PiTurneel.http"
local_addr = "127.0.0.1:80"

[client.services.https]
token = "JD@PiTurneel.https"
local_addr = "127.0.0.1:443"