[server]
bind_addr = "0.0.0.0:2333"
heartbeat_interval = 20

[server.transport]
type = "tcp"

[server.transport.tcp]
keepalive_interval = 8
keepalive_secs = 20

[server.services.http]
token = "JD@PiTurneel.http"
bind_addr = "0.0.0.0:80"

[server.services.https]
token = "JD@PiTurneel.https"
bind_addr = "0.0.0.0:443"