services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: always
    ports:
      - "3000:61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
    command: glances -w
  monitoring:
    container_name: monitoring
    image: monitoring:latest
    ports:
      - "8008:8008"
    environment:
      - PORT=8008
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8008/health || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
  nginxproxymanager:
    container_name: nginxProxyManager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
  rathole-client:
    container_name: rathole-client
    image: rapiz1/rathole:latest
    platform: linux/arm64
    restart: unless-stopped
    command: [ "--client", "/app/client.toml" ]
    network_mode: host
    volumes:
      - ./client.toml:/app/client.toml