services:
  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: always
    ports:
      - "3000:61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
    command: glances -w
    healthcheck:
      test: ["CMD", "python3", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:61208/api/3/status')"]
      interval: 1m
      timeout: 10s
      retries: 3

  monitoring:
    container_name: monitoring
    image: monitoring:latest
    ports:
      - "8008:8008"
    environment:
      - PORT=8008
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8008/health || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  nginxproxymanager:
    container_name: nginxProxyManager
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./beszel_agent_data:/var/lib/beszel-agent
    environment:
      LISTEN: 45876
      KEY: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEDkZ1eykBnHnGqzC29N6B5wb/DZc16RVXiaSRQmipmO'
      TOKEN: 10651-f129588aa-4baa-33570b898
      HUB_URL: http://80.225.248.6:3001
    healthcheck:
      test: ["CMD", "/beszel-agent", "-version"]
      interval: 1m
      timeout: 5s
      retries: 3