services:
  glances-new:
    image: nicolargo/glances:latest
    container_name: glances-new
    restart: always
    ports:
      - "3000:61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
    command: glances -w
  portainer-new:
    container_name: portainer-new
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9444"
      - "9000:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
  monitoring-new:
    container_name: monitoring-new
    image: monitoring:latest
    ports:
      - "8008:8008"
    environment:
      - PORT=8008
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8008/health || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
  nginxproxymanager_new:
    container_name: nginxProxyManager-new
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
volumes:
  portainer_data: