version: '3.8'

services:
  database:
    image: postgres:17-alpine
    container_name: printifyDbContainer
    restart: always
    env_file:
      - ../stack.env
    ports:
      - "5433:5432"
    volumes:
      - printify_dbVolumes:/var/lib/postgresql/data
  ktor-app:
    image: printify:latest
    container_name: printifyKtorContainer
    restart: always
    depends_on:
      - database
    env_file:
      - ../stack.env
    volumes:
      - printify_ktorVolumes:/uploads
    ports:
      - "8000:8000"
  web:
    image: printify-web:latest
    container_name: printifyWebsiteContainer
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:80" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    ports:
      - "8001:80"
volumes:
  printify_dbVolumes:
  printify_ktorVolumes: