version: '3.8'

services:
  database:
    image: postgres:17-alpine
    container_name: printifyDbContainer
    restart: always
    env_file:
      - ../stack.env
    ports:
      - "5433:5432"
    volumes:
      - printify_dbVolumes:/var/lib/postgresql/data
    # PostgreSql check using pg_isready
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  ktor-app:
    image: printify:latest
    container_name: printifyKtorContainer
    restart: always
    depends_on:
      database:
        condition: service_healthy # Wait for DB to be healthy, not just started
    env_file:
      - ../stack.env
    volumes:
      - printify_ktorVolumes:/uploads
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  web:
    image: printify-web:latest
    container_name: printifyWebsiteContainer
    restart: unless-stopped
    depends_on:
      ktor-app:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:80" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    ports:
      - "8001:80"
volumes:
  printify_dbVolumes:
  printify_ktorVolumes: